### ISSUE TITLE
20231031 중간 이전 전체 검토 결과

### ISSUE THREAD

**Issue by MisooKim2** [haegun2/PY202309#4]
### 없는 PDF 파일
- project/week8/search_engine.pdf
	- 위 파일 이름이나 위치를 다시 확인하세요. 보고서 채점이 수행되지 않습니다.

### 워닝 있음. 아래 파일/워닝메세지/솔루션을 확인하세요
- WARNING in challenge/week6/function
    - 22:Unused argument 'filename'	def save_tasks_to_file(task_list, filename):
    - 30:Unused argument 'filename'	def load_tasks_from_file(filename):
        - 함수 내에서 filename 변수가 사용되고 있지 않습니다. 해당 매개변수를 지우거나 사용하세요. 
- WARNING in challenge/week7/todo_extend
    - 16:Undefined variable 'i'	            task = task_list[i]
    - 17:Undefined variable 'i'	            print(f"{i+1}. {task}")
    - 15:Unused variable 'I'	        for I in range(len(task_list)):
        - for문에서는 대문자 i (I)로 변수를 생성했지만, 리스트 접근 시에는 소문자 i 를 사용하고 있습니다. 소문자로 통일해주세요. 
- WARNING in project/week8/search_engine
    - 22:Unused argument 'preprocessed_query'	def calc_similarity(preprocessed_query, preprocessed_sentences):   
    - 22:Unused argument 'preprocessed_sentences'	def calc_similarity(preprocessed_query, preprocessed_sentences):
         -  함수에서 매개변수로 받은 변수들을 사용하거나, 해당 변수들을 제거해주세요.

### 기능/코드 대비 주석이 부족합니다. 주석을 추가하거나 쪼개세요.
- Insufficient comments in challenge/week7/todo_extend

**Comment by haegun2** [comment]
제출되지 않은 보고서는 search 의 철자를 searh로 오타를 내어 제출되지 않았던 것으로 파악, 수정 후 재 커밋 했습니다.
WARNING in challenge/week6/function 은 fuunction warning 내용이 아닌, challenge/week7/todo warning 내용이었어서 해당 내용 수정 후 반영 했습니다.!
